# Generated by Django 5.1.3 on 2024-11-17 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.ImageField(default='No Photo', upload_to='users/photo/'),
        ),
    ]
