# Generated by Django 5.1.3 on 2024-11-17 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('authentication', '0002_user_photo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='UserSignUP',
        ),
    ]
