# Generated by Django 5.1.3 on 2024-11-17 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_rename_user_usersignup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersignup',
            name='password',
            field=models.CharField(max_length=50),
        ),
    ]
