# Generated by Django 5.1.3 on 2024-11-17 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_usersignup_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersignup',
            name='first_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='usersignup',
            name='password',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='usersignup',
            name='phone',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='usersignup',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('consumer', 'Consumer'), ('tricycler', 'Tricycler')], max_length=200),
        ),
        migrations.AlterField(
            model_name='usersignup',
            name='surname',
            field=models.CharField(max_length=200),
        ),
    ]
