# Generated by Django 5.1.3 on 2024-11-19 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_alter_usersignup_groups_alter_usersignup_hostel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersignup',
            name='address',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='usersignup',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='usersignup',
            name='first_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='usersignup',
            name='phone',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='usersignup',
            name='role',
            field=models.CharField(blank=True, choices=[('admin', 'Admin'), ('consumer', 'Consumer'), ('tricycler', 'Tricycler')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='usersignup',
            name='surname',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
